name: file_download_manager
description: Gerenciador de download multiplataforma
version: 0.1.0
homepage:
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_download_manager: ^0.5.3
  http: ^0.13.5
  mime_type: ^1.0.0
  path_provider: ^2.0.11
  share_plus: ^4.1.0
  mime: ^1.0.2
  file_android:
    git: https://github.com/guerder/file_android.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
